{% set version = '1.9' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tensorflow
  version: {{ version|replace("-", "_") }}

source:
  fn: tensorflow_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tensorflow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tensorflow/tensorflow_{{ version }}.tar.gz
  sha256: c341a7c8c72ddefa2803f20757d516449cfe6999e632c8dad2ebe0297f37643c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-config
    - r-jsonlite >=1.2
    - r-processx
    - r-reticulate >=1.10
    - r-rstudioapi >=0.7
    - r-tfruns >=1.0
    - r-yaml
  run:
    - r-base
    - r-config
    - r-jsonlite >=1.2
    - r-processx
    - r-reticulate >=1.10
    - r-rstudioapi >=0.7
    - r-tfruns >=1.0
    - r-yaml

test:
  commands:
    - $R -e "library('tensorflow')"           # [not win]
    - "\"%R%\" -e \"library('tensorflow')\""  # [win]

about:
  home: https://github.com/rstudio/tensorflow
  license: Apache 2.0
  summary: Interface to 'TensorFlow' <https://www.tensorflow.org/>,  an open source software
    library for numerical computation using data flow graphs. Nodes in the graph represent
    mathematical operations,  while the graph edges represent the multidimensional data
    arrays  (tensors) communicated between them. The flexible architecture allows you
    to deploy computation to one or more 'CPUs' or 'GPUs' in a desktop,  server, or
    mobile device with a single 'API'. 'TensorFlow' was originally developed by researchers
    and engineers working on the Google Brain Team  within Google's Machine Intelligence
    research organization for the  purposes of conducting machine learning and deep
    neural networks research, but the system is general enough to be applicable in a
    wide variety of other domains as well.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
