appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: BdI+vLhnk0vCfVFbxhLH+X6znDqbAC+Hvqvzyg7pYZ1sYULZTF9tvHDfNBgZmeAM+l8Zalo2Qcdh2b8kt3nn9F7PcQymxBZqzmNltl+GaCj7Toj5y0NOC8OIxTwOE4jivAtPQP9WgZm2AXb0/kVnWoqCm7u+QaN1BXlBPeHm7vXF3wP99n22Xmd8UqFO+FmiIMY3bUR1GGRyMPguz0jh4fL1NzIparsT7PNZsXa7wc1M8OJU/39Q+QFYDHFA0j1CaIWAvJx8u1uoFGREC8ITmg+W9qrsYQn2FIK/FwmnySNwKCENj+XQoVNVsaCgyQZ6iG7tG1389Kc/4+ydt+lF+wcjqZ26TrWbDfzDDIJFpHXXPfzwK0h8eoMQ7rKQZ4iM+3XyqJnt4Gu5EvLKqSz324B+cEgFyW3e2kltZOdECuaZ+kBBBIHAd/7DahoKB0RgWQLR9jlAMc1st4EnztZFdqzNGvo/rnfhyrI5XNydngr0q+ygRqOk24uxe7+6LsMV2r9jmJjS5t67KYH55EwLYsMAAJSl89zkiqkdR0eo2/7IHX8jbqpaQzdVaCK5JIQqZminf8VdU5KPzFZgMt70xsxlaYurkxBzl9LjVhIKKQS6mPSG68Ve0XV4WKsJCSwOq6qs45kJhidM2sov2K5f8rBV8DQWdXxTy1R5TCV4e6Y=
